# Generated by Django 5.0.2 on 2024-02-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_Name', models.CharField(max_length=50)),
                ('Admin_Email', models.CharField(max_length=50)),
                ('Admin_Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Prod_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_type_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
