# Generated by Django 5.0.2 on 2024-02-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place_Name', models.CharField(max_length=50)),
                ('District_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMTsApp.tbl_district')),
            ],
        ),
    ]
