# Generated by Django 5.0.2 on 2024-02-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0002_tbl_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ProductCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shop_Name', models.CharField(max_length=50)),
                ('Shop_Email', models.CharField(max_length=50)),
                ('Shop_Phone', models.CharField(max_length=50)),
                ('Shop_Address', models.CharField(max_length=50)),
                ('Shop_Photo', models.CharField(max_length=50)),
                ('Shop_License', models.CharField(max_length=50)),
                ('Shop_verStatus', models.CharField(max_length=50)),
                ('Shop_Passweord', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Name', models.CharField(max_length=50)),
                ('pro_Photo', models.CharField(max_length=50)),
                ('pro_Price', models.CharField(max_length=50)),
                ('Company_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMTsApp.tbl_productcompany')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock_Qty', models.CharField(max_length=50)),
                ('Stock_Date', models.CharField(max_length=50)),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMTsApp.tbl_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubCat_Name', models.CharField(max_length=50)),
                ('Category_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMTsApp.tbl_category')),
            ],
        ),
    ]
