# Generated by Django 5.0.2 on 2024-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0004_tbl_department_remove_tbl_product_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester_Name', models.CharField(max_length=50)),
            ],
        ),
    ]
