# Generated by Django 5.0.2 on 2024-02-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0006_tbl_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=50)),
                ('Course_Duretion', models.CharField(max_length=50)),
                ('Course_Nusem', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMTsApp.tbl_department')),
            ],
        ),
    ]
