# Generated by Django 5.0.2 on 2024-02-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0007_tbl_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_course',
            old_name='Course_Duretion',
            new_name='Course_Duration',
        ),
        migrations.RenameField(
            model_name='tbl_course',
            old_name='Course_Nusem',
            new_name='Course_Nusum',
        ),
        migrations.RenameField(
            model_name='tbl_course',
            old_name='dept_id',
            new_name='Department_Name',
        ),
    ]
