# Generated by Django 5.0.2 on 2024-03-06 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0009_tbl_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_course',
            name='Department_Name',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='Course_Name',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='Department_Name',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='Semester_Name',
        ),
        migrations.DeleteModel(
            name='tbl_Subject',
        ),
        migrations.DeleteModel(
            name='tbl_Course',
        ),
        migrations.DeleteModel(
            name='tbl_Department',
        ),
        migrations.DeleteModel(
            name='tbl_Semester',
        ),
        migrations.DeleteModel(
            name='tbl_Syllabus',
        ),
    ]
