# Generated by Django 5.0.2 on 2024-02-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMTsApp', '0009_tbl_syllabus'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CMTsApp.tbl_subcategory')),
            ],
        ),
    ]
